# Generated by Django 5.2.6 on 2025-09-23 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcondominio', '0006_infraccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('provider', models.CharField(choices=[('STRIPE', 'Stripe')], default='STRIPE', max_length=20)),
                ('provider_intent_id', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('REQUIRES_ACTION', 'Requires action'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], default='CREATED', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pago',
            name='medio',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('ONLINE_STRIPE', 'Online (Stripe)'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='referencia',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.UniqueConstraint(condition=models.Q(('referencia', ''), _negated=True), fields=('medio', 'referencia'), name='uniq_pago_medio_referencia'),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='cuota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_payments', to='smartcondominio.cuota'),
        ),
    ]
